### ISSUE TITLE
ENHANCEMENT OF LIBOT ADVENTURE 

### ISSUE THREAD

**Issue by cckole** [computationalcore/libot-adventure#1]
**Components**
LiBot Adventure is an open source game made with Unity 3D game engine. In this game , the Lithium spherical Robot is controlled using the up, down, left and right button that appears on the screen when the game is launched. The Lithium spherical Robot collect coin while avoiding mystical crates and stone monsters. In this game, I will like to make some suggestions to enhance each level in terms of how to make it easier for players to go about some difficulties encountered and make the game more fun and lively.

**PROPOSAL** 

Taking a look at LiBot Adventure, I discovered that the Lithium Robot is a magnetic component that attracts the crates to itself and once the crate touches it the game ends. Several crates falls at close interval and the player controls the lithium Spherical Robot away from the crates finding a clear way in other to move on by picking coin till it reaches the stipulated number to be picked to graduate to the next level. Having played this game for more than a month, I got to understand lots about it. The game has four levels and the highest level I’ve ever reached is level two, I couldn’t go beyond. I’ve tried several times but all to no avail. Also when I managed to get to level two and I later quit the game after lots of effort to proceed further, going back to it later will take me back to level one which is really not encouraging. That’s why I will like to suggest the following features.
1.	 Unlock the Island
2.	Life in the Box
3.	Life sustenance
4.	Hide the Lithium     

**UNLUCK THE ISLAND**: This game has four highlands which indicate each level. To unlock each island. Player must be able to finish the level in question. After the player must have completed one level and move to the other, the previous level is already completed and the current one is unlocked. Even though a player exit the game and come back to continue, he will be able to have access to the current island (level) and proceed.

**LIFE IN THE BOX**: There is this Box like crate that serves as the enemy to the Lithium Spherical Robot and we have lots of them falling from the sky to restrict the movement of the Lithium Robot and at the same time take life out of it. Having a life line falling at random in one of this crate will give the Robot an advantage to extend its life span. Once the Robot is opportune to hit any crate having this life, extra life is gained. Once the crate with L sign falls, the player will maneuver his way to hit it before it explodes and this will serve as a plus.

**LIFE SUSTENANCE**: This really refers to a kind of resources necessary for survival. This life sustenance once received will work for few seconds, like 10 seconds to be precise.  At this very time, the Lithium Robot will remain alive even with countless crate obstructions. Within this period, it would have the time and free will to gallivant around and pick coin till the time elapses after which it can be caught by the crates. This life sustenance will be difficult to pick in other to make it unique while playing the game.   

**HIDE THE LITHIUM** : Since the Lithium Robot(magnet) attracts death (crates) to itself, having a hiding place after toiling around will make the player get relaxed and plan on which route to follow again trying to avoid the crates further. The crates are so sensitive that within a second blink, they are all around the Lithium Robot. This strategy will have an impact on the game entirely.

**Mock ups / Examples**

The image showing unlock the Island where current game can be accessed and continued from where it's halted
<center>![unlock the island.png](https://ipfs.busy.org/ipfs/QmebzV8vadGJiqRb57uWH3RYQcXvTsrh4CJBssZQGJqyX6)</center>

This part shows the image of life in the Box where the Bot can access life to extend it's life span
<center>![life im the box.png](https://ipfs.busy.org/ipfs/Qmen9Vf912E4YjQvyyCnA9Vb4djdGiviRMexg4bmioDw9t)</center>

The image below shows life sustenance 
<center>![sustain life.png](https://ipfs.busy.org/ipfs/QmPgMAAgFQegrnvu4BhV5TN5d5rQWz3Zz9TyLJL9VBXMcd)</center>

This part shows the hiding of the Bot.
<center>![hide the bot.png](https://ipfs.busy.org/ipfs/QmRYfXEWgzNpBUiMS76KQgJpDFNZGpSsAPyCGWYyNsopVF)</center>

**BENEFITS**
From the above proposals, having the said features will allow the player continue from where he stops. From the experience gained while playing the game, this unlock the Island will make the game more interesting and player will not get bored and discouraged as the current level reached is not wiped out. Having this feature will erase the boredom encountered from the previous settings where game will restart after quitting it for some time.  
The life in the box will give the player the chance to move further and earn more coin to reach the next level compared to the current design where there’s no life to sustain the Lithium Robot. Only one life is present in the game, once the Lithium Robot is hit, the game goes over. This extra life will increase the life span of the Lithium Robot and this will make the player move further than expected. At least I will be able to move beyond level two after few months of playing the game.

The Life Sustenance will allow the Bot to live a little bit longer even with the reaction of Mr Death (Crates). This will give the Bot an extended free seconds to navigate and roam around freely picking coin without any fear of death.
Hiding the Lithium is another strategy to make the game even more interesting, once the Bot finds a place to hide itself, the crates will look like a fool and start searching every nook and cranny for the Bot. Since the Lithium Bot attracts them, the magnetic power will still drag them close to where its hiding and they will keep perambulating trying to kiss and kill. Apart from that, this feature will serve another purpose, a player can hide his Bot and leave the game to attend to other things. Since the game doesn’t have a pause button, this feature can also work in replacement.
With all these suggested features, I believe this game will be more fun if implemented in the next version.
Thanks.

**Comment by computationalcore** [comment]
Thanks cckole, those are pretty good enhancements and I will probably implement some in the future. 

I already have done some updates that didn't publish yet, I added difficulty levels, because as you said, the game is pretty hard to play. I shall publish it asap. 

Thank you

**Comment by cckole** [comment]
i will be glad to see the updates as soon as possible. Thanks for your response.
